# Generated by Django 4.2.5 on 2023-10-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="一级菜单名称")),
                ("icon", models.CharField(max_length=32, verbose_name="图标")),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
                ("url", models.CharField(max_length=128, verbose_name="含正则的URL")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="url的别名"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        help_text="null表示不是菜单，非null表示是二级菜单",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rbac.menu",
                        verbose_name="所属菜单",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        blank=True,
                        help_text="对于非菜单权限需要选择一个可以成为菜单的权限，用户做默认展开",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="rbac.permission",
                        verbose_name="关联的权限",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="角色名称")),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="rbac.permission", verbose_name="拥有的所有权限"
                    ),
                ),
            ],
        ),
    ]
